### ISSUE TITLE
Bonsai asset not updated

### ISSUE THREAD

**Issue by nmollerup** [sardinasystems/sensu-go-systemd-check#61]
Latest version according to bonsai is 0.28.0 but there is no release assets.

The latest release on github is 0.30.0, but that is not even shown on bonsai.

https://bonsai.sensu.io/assets/sardinasystems/sensu-go-systemd-check

**Comment by vooon** [comment]
Unsure, it's stuck on building. Triggered manual rebuild, lets see if it helps.

**Comment by nmollerup** [comment]
Awesome, all seems ok now. Except the 0.28.0 assets arent there. bonsai is a bit buggy I guess.
